name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint || echo "Lint step not configured fully"
      - name: Type check
        run: npx tsc --noEmit
      - name: Build
        run: npm run build
      - name: Export static site
        run: npm run export
      - name: List exported files (debug)
        run: |
          echo "Exported artifact contents:" && ls -R out | head -n 100
